import Link from "next/link";

export const metadata = { title: "Terms of Service — ShipFlow AI" };

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-20">
      <Link
        href="/"
        className="text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        ← Back to home
      </Link>
      <h1 className="mt-6 font-display text-3xl font-bold tracking-tight text-foreground">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated {new Date().getFullYear()}
      </p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
        <p>
          By creating an account and using ShipFlow AI, you agree to these
          terms. ShipFlow AI helps teams take features from request to shipped
          code through an AI-assisted, human-approved workflow.
        </p>
        <section>
          <h2 className="mb-2 text-base font-semibold text-foreground">
            Acceptable use
          </h2>
          <p>
            Use the platform only for lawful purposes and connect only
            repositories you are authorized to access. You are responsible for
            the content created in your workspaces.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-base font-semibold text-foreground">
            AI-generated content
          </h2>
          <p>
            PRDs, tasks, and reviews are generated by AI as assistance. A human
            reviewer makes the final approval decision before any release. You
            are responsible for verifying AI output before shipping.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-base font-semibold text-foreground">
            Billing
          </h2>
          <p>
            Paid plans are billed via the configured payment provider. Usage
            limits apply per plan and reset each billing cycle.
          </p>
        </section>
        <p className="text-xs text-muted-foreground/70">
          This is a demo application; these terms are provided as a template.
        </p>
      </div>
    </main>
  );
}
